version: '3.9'

services:

  mysql:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${PROJECT}-mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${PROJECT}
    volumes:
      - ../:/var/www/html
      - db:/var/lib/mysql
      - ./.bashrc:/root/.bashrc
    networks:
      - wordpress

  wordpress:
#   image: wordpress:php${PHP_VERSION}
    container_name: ${PROJECT}-wordpress
    build:
      context: .
      dockerfile: wordpress.dockerfile
      args:
        - PHP_VERSION=php${PHP_VERSION}
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: ${PROJECT}
      WORDPRESS_TABLE_PREFIX: ${ABBR:-wp}_
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
    volumes:
      - ../:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./.bashrc:/root/.bashrc
    networks:
      - wordpress

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT}-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    networks:
      - wordpress

  mailhog:
    container_name: ${PROJECT}-mailhog
    image: mailhog/mailhog
#    ports:
#      - "1025:1025"
#      - "8025:8025"
    restart: unless-stopped
    networks:
      - wordpress

networks:
  wordpress:
    name: ${PROJECT}

volumes:
  db:
    name: ${PROJECT}
